//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace is_takip_proje.Entity
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DB_IsTakipEntities : DbContext
    {
        public DB_IsTakipEntities()
            : base("name=DB_IsTakipEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Tbl_Admin> Tbl_Admin { get; set; }
        public virtual DbSet<Tbl_Departmanlar> Tbl_Departmanlar { get; set; }
        public virtual DbSet<Tbl_Firmalar> Tbl_Firmalar { get; set; }
        public virtual DbSet<Tbl_GorevDetaylar> Tbl_GorevDetaylar { get; set; }
        public virtual DbSet<Tbl_Gorevler> Tbl_Gorevler { get; set; }
        public virtual DbSet<Tbl_Personel> Tbl_Personel { get; set; }
        public virtual DbSet<Tbl_Cagri> Tbl_Cagri { get; set; }
        public virtual DbSet<Tbl_CagriDetay> Tbl_CagriDetay { get; set; }
    }
}
